//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PITON 2.rc
//
#define pt_DIFF_MID                     2
#define pt_DIFF_HARD                    3
#define pt_DIFF_HCOR                    4
#define pt_ON                           5
#define pt_OFF                          6
#define pt_MODE_ONE                     7
#define pt_MODE_FREND                   8
#define pt_MODE_ENEMS                   9
#define pt_MODE_SURR                    10
#define pt_GRID_RED                     11
#define pt_GRID_BLACK                   12
#define pt_LOCATOR_ALL                  13
#define pt_LOCATOR_60                   14
#define pt_LOCATOR_30                   15
#define pt_LOCATOR_15                   16
#define pt_DONE                         17
#define pt_CANCEL                       18
#define IDI_ICON                        101
#define IDR_MAINMENU                    102
#define IDD_DRIVERDIALOG                105
#define IDD_DIALOG1                     106
#define IDC_EMPTY                       109
#define IDC_DRIVERLIST                  1000

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40014
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
