


#define	SHIFT		= (-0x20)
#define CTRL		= (-0x60)
#define ALT		= (& 0xFF00)
WORD const key_A		= 0x1E61;
WORD const key_B		= 0x3062;
WORD const key_C		= 0x2E63;
WORD const key_D		= 0x2064;
WORD const key_E		= 0x1265;
WORD const key_F		= 0x2166;
WORD const key_G		= 0x2267;
WORD const key_H		= 0x2368;
WORD const key_I		= 0x1769;
WORD const key_J		= 0x246A;
WORD const key_K		= 0x256B;
WORD const key_L		= 0x266C;
WORD const key_M		= 0x326D;
WORD const key_N		= 0x316E;
WORD const key_O		= 0x186F;
WORD const key_P		= 0x1970;
WORD const key_Q		= 0x1071;
WORD const key_R		= 0x1372;
WORD const key_S		= 0x1B73;
WORD const key_T		= 0x1474;
WORD const key_U		= 0x1675;
WORD const key_V		= 0x2B76;
WORD const key_W		= 0x1177;
WORD const key_X		= 0x2D78;
WORD const key_Y		= 0x1579;
WORD const key_Z		= 0x2C7A;


#define	fSHIFT		= (0x19)
#define fCTRL		= (0x23)
#define fALT		= (0x2D)
WORD const key_F1		= 0x3B00;
WORD const key_F2		= 0x3C00;
WORD const key_F3		= 0x3D00;
WORD const key_F4		= 0x3E00;
WORD const key_F5		= 0x3F00;
WORD const key_F6		= 0x4000;
WORD const key_F7		= 0x4100;
WORD const key_F8		= 0x4200;
WORD const key_F9		= 0x4300;
WORD const key_F10		= 0x4400;
WORD const key_F11		= 0x4500;
WORD const key_F12		= 0x4600;


WORD const key_1		= 0x0231;
WORD const key_2		= 0x0231;
WORD const key_3		= 0x0231;
WORD const key_4		= 0x0231;
WORD const key_5		= 0x0231;
WORD const key_6		= 0x0231;
WORD const key_7		= 0x0231;
WORD const key_8		= 0x0231;
WORD const key_9		= 0x0231;
WORD const key_0		= 0x0231;
WORD const key_minus	= 0x0231;
WORD const key_plus		= 0x0231;
WORD const key_vert		= 0x2B7C;
WORD const key_backspace= 0x0231;
WORD const key_enter	= 0x0231;